// This file is automatically generated by stac init.

import 'package:stac/stac_core.dart';

/// Default [StacOptions] for use with your stac project.
///
/// Use this to initialize stac **before** calling [runApp].
///
/// Example:
/// ```dart
/// import 'package:flutter/material.dart';
/// import 'package:stac/stac.dart';
/// import 'default_stac_options.dart';
///
/// void main() {
///   Stac.initialize(options: defaultStacOptions);
///
///   runApp(...);
/// }
/// ```
StacOptions get defaultStacOptions => StacOptions(
  name: 'stac_test_pro',
  description: '',
  projectId: 'wmal7BdlQ4f0VMiUuZQJ',
  sourceDir: 'stac',
  outputDir: 'stac/.build',
);
